### PR TITLE
add python 3.11 and 3.12 support

### PR DESCRIPTION
**Pull request by dneuhaeuser-zalando**
This is an attempt to fix https://github.com/TkTech/pysimdjson/issues/112

I say attempt because I have essentially no knowledge of cython but I figured it can't be that difficult to try re-generating the cython generated code. It does seem to do the job on my machine as in tests pass with this on python 3.12 on Mac with an M1.

Edit: Just noticed workflow might not trigger here but it does for my fork (I'm not used to GH actions), it works everywhere else to except ubuntu on 3.6 but that seems to be some sort of issue with actions https://github.com/dneuhaeuser-zalando/pysimdjson/actions/runs/6488676971

### CODE REVIEW

**Comment by itayplav** [comment]
Workaround until this PR this is merged:
```bash
pip install git+https://github.com/TkTech/pysimdjson.git@refs/pull/113/head
```

**Comment by william-silversmith** [comment]
Thanks for the wonderful library and all the work you've put in! A few of my libraries are crashing their integration tests due to lacking py312 support. Would it be possible to merge and release this?

Again, thanks for all you do!

**Comment by clbarnes** [comment]
It would also be great to specify the build-time dependencies in a pyproject.toml like this:

```toml
[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"
```

Cython is somewhat optional as it's only used in certain cases, but for build deps I'd rather be belt-and-braces.

**Comment by TkTech** [comment]
Thanks for your contribution. A more complete update is in master and will be released as version 6.0.0. Your MR updates the tests, not the release stages.

Release is currently blocked only by https://github.com/simdjson/simdjson/issues/2117

**Pull request closed without merging**
