### PR TITLE
fix(ci): wheels for Python 3.9 ARM and missing `errors.h` from MANIFEST for source build

### LINKED ISSUE #84: ARM build failing and ARM python 3.9 missing wheels
The ARM build is failing due to an `error.h` error. The Python 3.9 wheels for ARM/aarch64 is missing as well.

### PR DESCRIPTION
**Pull request by ExecutionSpeed**
Resolves #84.

### CODE REVIEW

**Comment by TkTech** [comment]
Sorry for the delay, the CI wasn't running on PRs and I didn't have time to look at it until now. Let me give it a kick and get it running.

**Comment by ExecutionSpeed** [comment]
> Sorry for the delay, the CI wasn't running on PRs and I didn't have time to look at it until now. Let me give it a kick and get it running.

@TkTech No problem at all. Merged the latest CI related change from master and triggered the CI. It was able to successfully build 3.9 wheels as well for `aarch64`.

**Comment by ExecutionSpeed** [comment]
@TkTech Any chance we can merge this if it's looking good? Blocked on our ARM instances currently.

**Comment by JonathanGrant** [comment]
Can we merge this?

**Comment by ExecutionSpeed** [comment]
Can we get a `4.0.1` release please?

**Pull request merged**
